### ISSUE TITLE
Document OA Machine changes required

### ISSUE THREAD

**Issue by migurski** [openaddresses/submit-ui#1]
This is a draft of the upgrades that [OA Machine](https://github.com/openaddresses/machine) needs to support TriMet and MOD work:

https://docs.google.com/document/d/1NKvFblj_-rAhL7k_65vBV37NTWNyysri5dQRnjMrZVI/edit#

Summary:

- Refactor the machine codebase to generate these small extracts up-front and more quickly, so that they can be used as part of an iterative interaction with OA
- Extend and document Machine API to support a Mapzen-run wizard-style interface

**Comment by trescube** [comment]
This has been superseded by the submit-service project
