### ISSUE TITLE
Design tweaks

### ISSUE THREAD

**Issue by souperneon** [openaddresses/submit-ui#108]
Overall:
- [x] Red asterisk https://github.com/mapzen/mobility-on-demand-sandbox-contributions/issues/73
- [x] Add 2em margin-top to the start of the form fields on every page (below page title)
- [x]  Add 4em margin above the next and back buttons on every page
- [x] Button heights 2em
- [x] Standardize default text and placeholder text color to #bfbfbf (currently inconsistent)
- [x] add a black semi transparent background behind the steps
- [x] add white space at the bottom of every page (maybe like 150-200px)

Colors: (variable names are just examples, feel free to change)
$error (error, required, 'remove' - text and icons) #e50b17 red
$error-hover #94070f
$success (success, 'add' - text and icons) #69cb01 green
$success-hover #468701
$link (text links, 'split column', 'join column' - text and icons) #1b90f9 blue
$link-hover #0564ba
$button-next #00b5ad
$button-next-hover #00938d
$button-back #777777
$button-back-hover #444444

Step 1:
![screen shot 2017-11-22 at 1 41 15 pm](https://user-images.githubusercontent.com/6125224/33145930-389b2126-cf90-11e7-93c4-6a289f9682c3.png)

- [x] Make URL field wider
- [x] Make <hr> around 'OR' narrow
- [x] Make letter spacing 1px for the progress bar
- [x] Add padding above progress bar text
- [x]  Number the steps and rename (see screenshot)
![screen shot 2017-11-22 at 1 19 12 pm](https://user-images.githubusercontent.com/6125224/33143455-e9744cf6-cf87-11e7-936a-cecd019cfd51.png)

Step 2:
- [x] Make "license info" and "data info" separate boxes
- [x]  Yes, No, I don't know colors (refer transit land)
- [x] Choose from license or provide link, make radio and stack vertically
- [x] Make "Choose from list of license" radio button preselected
- [x] Nice to Have: have both options visible and when user interacts with one, select radio button 

Step 3:
![mod_1](https://user-images.githubusercontent.com/6125224/33147892-aaf679a8-cf97-11e7-82ca-86fe9fe91f9c.png)
![mod_2](https://user-images.githubusercontent.com/6125224/33147893-ab001bfc-cf97-11e7-8d81-4fbb6bcc4d20.png)

- [x] 'This is a small sample of the data for preview' above the table
- [x]  < Number    Street > - Add navigation within the data format step
- [x] Button language "Join columns" "Split column"
- [x] Make "Join columns" "Split column" show up right away
- [x] Style "Join columns" "Split column" as text links with icons in blue (see screenshot) 
- [x] For Join state, keep dropdown format same but add new dropdowns below
- [x] In dropdowns, change 'example value' to 'sample value'
- [x] Make required star included with house number field (narrower column)

Step 5:
- [x] Make 'Edit' style link with icon in blue
- [x]  Capitalize 'True' in the attribution 
- [x]  'Edit' link font size is smaller. Make it same as default text and bold (like housenumber, unit etc. in the table)

Success:
- [x] Center align text

Future
- [x]  For columns that cannot be split, don't show all the options?

**Comment by mkong0216** [comment]
In my branch (mkong0216/design-tweaks) I did not make the button heights 2em because it causes the semantic-ui buttons' text to be uncentered. I did, however, make use of semantic-ui's `compact` class which makes the buttons have less padding. I can make it smaller by using the `small` class. For now I will check it as done.

**Comment by mkong0216** [comment]
![Screen Shot 2017-12-14 at 5.02.50 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599c714cef464a001ac120a2/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455f76b7191a37df112294f5a5f5ecc3c4a4356bcbbd671f3e57862804e0ee4d63c5a25c76f12aab8d319b601ba2688478ce4b58b18d2f42f67b6d5db1063474f4dcbed5727a19141c95df748e3455ca5113164e2752431.png)

@souperneon is this what you mean by a semi-transparent black background behind the steps? This is at 0.3 transparency, I think it looks better without the background though. Maybe I need to go more transparent or less transparent? 

I also have been meaning to ask you what you meant by default text that needs to be standardized? Haha, sorry don't really know what is considered default text.

**Comment by souperneon** [comment]
Exactly :) Let's bump it up to 0.5 so that the text is more readable.

Whoops, I should have been more explicit.
- Default text color is all body and paragraph text. I think it should be #444
- Placeholder text and helper text inside text fields should be #bfbfbf across the board.

(I remember seeing some other values before I left, but you might've already taken care of it)

**Comment by mkong0216** [comment]
Ah sorry one more question then, would labels be considered default text or helper text? Like the labels of each field the user has the input?

**Comment by mkong0216** [comment]
hey @meghanhade do you mind telling me which file I should be in to change "example value" to "sample value" in the data-formats page? I'm not seeing it in `models/submission.js`

**Comment by souperneon** [comment]
Labels are their own thing. The easiest styling for labels can be to use the same text size as default text but a bold font weight.

**Comment by mkong0216** [comment]
- [ ] More Info: make "Choose from list of license" default checked

**Comment by mkong0216** [comment]
@souperneon hey I was able to do the nice to have for data-format where both inputs are displayed and when you interact with one it automatically selects the corresponding radio button (see #136) and was wondering if you still wanted the "choose license" radio button to be preselected?

**Comment by souperneon** [comment]
Yeah I think so, and the other one can be made to look inactive in some way… just reduced opacity is fine with semantic UI doesn't have a preset. I'm around if you want to look at it together

**Comment by meghanhade** [comment]
@mkong0216 can this issue be closed now?

**Comment by mkong0216** [comment]
Yes, I think so. There's only the "In dropdowns, change 'example value' to 'sample value'" for the Data Format page left but I don't know which file to go to in order to change that.
