### ISSUE TITLE
Successful submission (page 9) UI

### ISSUE THREAD

**Issue by meghanhade** [openaddresses/submit-ui#29]
- [x] Successful submission message, with explanation of next steps
- [x] remove steps 1-5 from the top
- [x]  SUCCESS!
Thank you for submitting data to OpenAddresses.
Next, the OpenAddresses team will review your submission and then import it into the OpenAddresses database. You can track the progress of your submission here [Link to GitHub PR]. You will be notified at the email address you provided when the import process is complete.

** If the submit flow is part of the OpenAddresses website, do nothing. But if it lives independently, add a button at the bottom of the thank you page to return to "Submit data" "OpenAddresses" **

**Comment by mkong0216** [comment]
@meghanhade: Hey! Mind if I assign this to myself? 
If so, can you list out the next steps after submitting that I should include?
