### ISSUE TITLE
Form validations follow up  ( + data validation)

### ISSUE THREAD

**Issue by hanbyul-here** [openaddresses/submit-ui#42]
- [x] Style error as a part of the element
- [x] Check dropdown value 
- [x] Make the changeset not to validate user's inputs all the times. (Or at least display error only when the button is hit)

**Comment by hanbyul-here** [comment]
- [ ] take frequency out from the mandatory validation list
- [ ] enable back button (currently, both of nav button try to validate the forms and it makes impossible to navigate back)

**Comment by meghanhade** [comment]
- [ ] when `yes` is selected for License, require `License URL`
- [ ] when `yes` is selected for Attribution, require a`ttribution text`

**Comment by mkong0216** [comment]
- [ ] Require either data link or data upload before moving on from `Intro` page to `More Info` page

**Comment by hanbyul-here** [comment]
Form validation can only validate the value inside of forms against model property. We def should check if there is any data mounted before going from `intro` to `more info`. However I think it would be more data check than form validation.

**Comment by mkong0216** [comment]
@hanbyul-here : I noticed that if you don't even select the `email address` input box on the `Contact` page and just select `next`, the form validation doesn't work and it allows you to proceed to `Review`. Not sure if it's just me...

**Comment by meghanhade** [comment]
@mkong0216 @hanbyul-here  I noticed the same thing.

**Comment by meghanhade** [comment]
- [ ] In data-format, validate that at least one additional field has been selected for `join` or that an additional function has been selected for `split`. If not, prompt user to do so or cancel split/join.

**Comment by hanbyul-here** [comment]
@mkong @meghanhade ah Thanks for catching. That was because changeset-validation was not validating the very initial value. Now all values should be validated before going through the process in this pr https://github.com/mapzen/mobility-on-demand-sandbox-contributions/pull/139

**Comment by hanbyul-here** [comment]
@meghanhade :raised_back_of_hand: question: is it possible for `attribution_text` to exist when `license` was selected as `no` ?

**Comment by souperneon** [comment]
- [ ] When user clicks Join or Split without selecting a column from dropdown, show error message above dropdown in the same style as step 1. "Select a column name below to Join or Split"

**Comment by mkong0216** [comment]
@hanbyul-here I changed the way users can add a license (more-info page) in PR #165 but it leads to the form validation not working right and I'm not quite sure how to fix it. 

If you first choose a license (the "Choose" radio button gets selected) but then select the "Provide" radio button and then select the "Choose" radio button again, even though there's a license chosen, the "License Error 1" message gets printed. 

If that makes sense...

**Comment by hanbyul-here** [comment]
Where is your change now Mandy?

**Comment by mkong0216** [comment]
@hanbyul-here which branch? It's in PR #165
